---
version: "2.1"
services:
  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=nextcloud #optional
      - MYSQL_USER=xxken #optional
      - MYSQL_PASSWORD=xxkenxyz #optional
      - REMOTE_SQL=http://URL1/your.sql,https://URL2/your.sql #optional
    volumes:
      - /srv/dev-disk-by-id-usb-JMicron_Tech_W3TEMQSE-0-0-part1/yppa-500gb/nextcloud:/config #INI SAMA INIIN DENGAN DISK DI BANGAIN nextcloud.yaml DIBAGIAN CONFIGNYA BROW OKEE 
    ports:
      - 3306:3306
    restart: unless-stopped
